// ─────────────────────────────────────
// build-env.js — Vercel ビルド時に env.js を自動生成
// Vercel Dashboard → Settings → Environment Variables に
// 各キーを登録しておくこと
// ─────────────────────────────────────

const fs = require('fs');

const env = {
  // Firebase
  FIREBASE_API_KEY:             process.env.FIREBASE_API_KEY             || '',
  FIREBASE_AUTH_DOMAIN:         process.env.FIREBASE_AUTH_DOMAIN         || '',
  FIREBASE_PROJECT_ID:          process.env.FIREBASE_PROJECT_ID          || '',
  FIREBASE_STORAGE_BUCKET:      process.env.FIREBASE_STORAGE_BUCKET      || '',
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  FIREBASE_APP_ID:              process.env.FIREBASE_APP_ID              || '',
  FIREBASE_MEASUREMENT_ID:      process.env.FIREBASE_MEASUREMENT_ID      || '',

  // Gemini AI
  GEMINI_KEY_CERT:              process.env.GEMINI_KEY_CERT              || '',
  GEMINI_KEY_INTERVIEW:         process.env.GEMINI_KEY_INTERVIEW         || '',
};

// 未設定のキーをチェック
const missing = Object.entries(env).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.warn('[build-env] ⚠️  未設定の環境変数:', missing.join(', '));
} else {
  console.log('[build-env] ✅ すべての環境変数が設定されています');
}

const content = `// Auto-generated by build-env.js — do not edit
// Vercel build: ${new Date().toISOString()}
window.__ENV__ = ${JSON.stringify(env, null, 2)};
`;

fs.writeFileSync('env.js', content, 'utf8');
console.log('[build-env] env.js を生成しました');
